window.NAME_DB = {
    fantasy: {
        royalty: {
            m: ["아서|Arthur", "윌리엄|William", "리처드|Richard", "에드워드|Edward", "알렉산더|Alexander", "루이|Louis", "헨리|Henry", "프레데릭|Frederick", "레오|Leo", "막시밀리안|Maximilian", "필립|Philip", "찰스|Charles", "조지|George", "알라릭|Alaric", "테오도르|Theodore", "발레리우스|Valerius", "아우구스투스|Augustus", "세바스찬|Sebastian", "율리우스|Julius", "카시우스|Cassius", "데미안|Demian", "루시안|Lucian", "아드리안|Adrian", "줄리안|Julian", "베네딕트|Benedict", "콘스탄틴|Constantine", "가브리엘|Gabriel", "미카엘|Michael", "라파엘|Raphael", "오스카|Oscar", "클로비스|Clovis", "샤를마뉴|Charlemagne", "피핀|Pepin", "로타르|Lothair", "콘라드|Conrad", "오토|Otto", "지기스문트|Sigismund", "페르디난드|Ferdinand", "알폰소|Alfonso", "펠리페|Felipe", "카를로스|Carlos", "프란시스|Francis", "제임스|James", "해롤드|Harold", "에드문드|Edmund", "앨버트|Albert", "빅터|Victor", "니콜라스|Nicholas", "블라디미르|Vladimir", "구스타프|Gustav", "크리스티안|Christian", "레오폴드|Leopold", "루드비히|Ludwig", "프란츠|Franz", "루돌프|Rudolf", "발트해머|Waldemar", "카시미르|Casimir", "마티아스|Matthias", "스테판|Stefan", "이반|Ivan", "아게실라우스|Agesilaus", "레오니다스|Leonidas", "크세르크세스|Xerxes", "다리우스|Darius", "키루스|Cyrus", "트라야누스|Trajan", "하드리아누스|Hadrian", "마르쿠스|Marcus", "콤모두스|Commodus", "셉티미우스|Septimius", "카라칼라|Caracalla", "디오클레티아누스|Diocletian", "발렌티니안|Valentinian", "테오도시우스|Theodosius", "유스티니아누스|Justinian", "벨리사리우스|Belisarius", "헤라클리우스|Heraclius", "바실리우스|Basilius", "레오|Leo", "로마누스|Romanus", "알렉시우스|Alexius", "마누엘|Manuel", "안드로니쿠스|Andronicus", "볼레슬라프|Boleslaw", "미에슈코|Mieszko", "라디슬라프|Ladislav", "벨라|Bela", "이스트반|Istvan", "칼만|Kalman", "러요슈|Lajos"],
            f: ["엘리자베스|Elizabeth", "빅토리아|Victoria", "이사벨라|Isabella", "마틸다|Matilda", "아델라|Adela", "베아트리스|Beatrice", "샬롯|Charlotte", "엘레노어|Eleanor", "마가렛|Margaret", "캐서린|Catherine", "소피아|Sophia", "아나스타샤|Anastasia", "줄리아|Julia", "클라우디아|Claudia", "발렌티나|Valentina", "세실리아|Cecilia", "오필리아|Ophelia", "코델리아|Cordelia", "제네비브|Genevieve", "로잘린드|Rosalind", "비비안|Vivian", "세라피나|Seraphina", "아우렐리아|Aurelia", "루시아|Lucia", "헬레나|Helena", "다이아나|Diana", "카밀라|Camilla", "오로라|Aurora", "실비아|Sylvia", "마리|Marie", "아델라이드|Adelaide", "콘스탄스|Constance", "이디스|Edith", "필리파|Philippa", "조안|Joan", "앤|Anne", "크리스티나|Christina", "빌헬미나|Wilhelmina", "앙투아네트|Antoinette", "조세핀|Josephine", "테레사|Theresa", "이레네|Irene", "제니아|Xenia", "타티아나|Tatiana", "올가|Olga", "잉그리드|Ingrid", "아스트리드|Astrid", "브리짓|Bridget", "우르술라|Ursula", "클레멘타인|Clementine", "플로라|Flora", "블랑쉬|Blanche", "가브리엘라|Gabriella", "알렉산드라|Alexandra", "캐롤라인|Caroline", "루이즈|Louise", "엠마뉴엘|Emmanuelle", "비올라|Viola", "미란다|Miranda", "리건|Regan", "제노비아|Zenobia", "클레오파트라|Cleopatra", "네페르티티|Nefertiti", "하트셉수트|Hatshepsut", "아그리피나|Agrippina", "메살리나|Messalina", "옥타비아|Octavia", "리비아|Livia", "루크레치아|Lucretia", "베로니카|Veronica", "우라니아|Urania", "칼리오페|Calliope", "에우로파|Europa", "안티고네|Antigone", "이스메네|Ismene", "일렉트라|Electra", "이피게니아|Iphigenia", "라비니아|Lavinia", "디도|Dido", "기네비어|Guinevere", "이졸데|Isolde", "모르간|Morgan", "님에|Nimue", "일레인|Elaine", "이그레인|Igraine", "모가즈|Morgause", "그리젤다|Griselda", "고디바|Godiva", "로웨나|Rowena", "에오윈|Eowyn"],
            s: ["라이온하트|Lionheart", "골드메인|Goldmane", "실버쏜|Silverthorn", "블랙우드|Blackwood", "윈터본|Winterbourne", "서머셋|Somerset", "하이윈드|Highwind", "스톰가드|Stormguard", "아이언사이드|Ironside", "로즈블러드|Roseblood", "킹스베인|Kingsbane", "로열|Royal", "크라운|Crown", "발루아|Valois", "튜더|Tudor", "하노버|Hanover", "윈저|Windsor", "랭카스터|Lancaster", "요크|York", "스튜어트|Stuart", "부르봉|Bourbon", "합스부르크|Habsburg", "메디치|Medici", "로마노프|Romanov", "호엔촐레른|Hohenzollern", "사보이|Savoy", "그리말디|Grimaldi", "오렌지|Orange", "나소|Nassau", "룩셈부르크|Luxembourg", "선파이어|Sunfire", "문위스퍼|Moonwhisper", "스타폴|Starfall", "던시커|Dawnseeker", "나이트셰이드|Nightshade", "레이븐스크로프트|Ravenscroft", "애쉬다운|Ashdown", "쏜|Thorne", "스털링|Sterling", "크롬웰|Cromwell", "싱클레어|Sinclair", "몽고메리|Montgomery", "하워드|Howard", "퍼시|Percy", "네빌|Neville", "보퍼트|Beaufort", "모티머|Mortimer", "스탠리|Stanley", "탈봇|Talbot", "헤이스팅스|Hastings", "버킹엄|Buckingham", "베드포드|Bedford", "클라렌스|Clarence", "글로스터|Gloucester", "켄트|Kent", "콘월|Cornwall", "웨일즈|Wales", "알바니|Albany", "로스|Ross", "마치|March", "드래곤하트|Dragonheart", "피닉스윙|Phoenixwing", "그리핀클로|Griffinclaw", "유니콘혼|Unicornhorn", "스타게이저|Stargazer", "선라이더|Sunrider", "문워커|Moonwalker", "스카이본|Skyborn", "어스셰이커|Earthshaker", "씨워커|Seawalker", "프로스트본|Frostborn", "플레임하트|Flameheart", "썬더로드|Thunderlord", "스톰브링어|Stormbringer", "윈드러너|Windrunner", "돈브링어|Dawnbringer", "더스크워커|Duskwalker", "나이트폴|Nightfall", "데이브레이크|Daybreak", "라이트브링어|Lightbringer", "섀도우헌터|Shadowhunter", "블러드문|Bloodmoon", "실버문|Silvermoon", "골든선|Goldensun", "아이언포지|Ironforge", "스틸가드|Steelguard", "스톤월|Stonewall", "우드워드|Woodward", "리버송|Riversong", "레이크뷰|Lakeview"]
        },
        knight: {
            m: ["랜스|Lance", "가웨인|Gawain", "퍼시벌|Percival", "트리스탄|Tristan", "헥토르|Hector", "아킬레스|Achilles", "롤랑|Roland", "올리버|Oliver", "제라드|Gerard", "볼드윈|Baldwin", "고드프리|Godfrey", "레이몬드|Raymond", "탄크레드|Tancred", "보에몽|Bohemond", "로버트|Robert", "가이|Guy", "시몬|Simon", "휴|Hugh", "제프리|Geoffrey", "스테판|Stephen", "로저|Roger", "윌터|Walter", "길버트|Gilbert", "버나드|Bernard", "아놀드|Arnold", "레오파드|Leopard", "울프|Wolf", "베어|Bear", "호크|Hawk", "팔콘|Falcon", "켄드릭|Kendrick", "로데릭|Roderick", "세드릭|Cedric", "테오도릭|Theodoric", "레오프릭|Leofric", "울프릭|Wulfric", "에발트|Ewald", "게르하르트|Gerhardt", "하르트무트|Hartmut", "라이너|Rainer", "폴커|Volker", "건터|Gunther", "하겐|Hagen", "지그프리드|Siegfried", "디트리히|Dietrich", "힐데브란트|Hildebrand", "케인|Kane", "드레이크|Drake", "그리핀|Griffin", "렉스|Rex", "막시무스|Maximus", "타이투스|Titus", "마르쿠스|Marcus", "루키우스|Lucius", "플라비우스|Flavius", "발레리안|Valerian", "오리온|Orion", "아약스|Ajax", "제이슨|Jason", "헤라클레스|Hercules", "갤러해드|Galahad", "보어스|Bors", "베디비어|Bedivere", "케이|Kay", "가레스|Gareth", "가헤리스|Gaheris", "팔로미데스|Palomides", "사피르|Safir", "세그와리데스|Segwarides", "다이나단|Dinadan", "다고넷|Dagonet", "모홀트|Morholt", "라모락|Lamorak", "펠리노어|Pellinore", "아그라베인|Agravain", "모드레드|Mordred", "토르|Tor", "엑터|Ector", "라이언|Lionel", "루칸|Lucan", "비요른|Bjorn", "라그나|Ragnar", "롤로|Rollo", "아이바|Ivar", "에릭|Erik", "하랄드|Harald", "스벤|Sven", "크누트|Cnut", "레이프|Leif", "소린|Thorin"],
            f: ["잔|Jeanne", "브리|Bree", "카산드라|Cassandra", "발키리|Valkyrie", "아테나|Athena", "벨로나|Bellona", "카밀라|Camilla", "브래드라만테|Bradamante", "마르피사|Marpissa", "클로린다|Clorinda", "브룬힐데|Brunhilde", "시그룬|Sigrun", "로즈|Rose", "릴리|Lily", "아이리스|Iris", "바이올렛|Violet", "재스민|Jasmine", "데이지|Daisy", "포피|Poppy", "홀리|Holly", "아이비|Ivy", "헤이젤|Hazel", "윌로우|Willow", "로완|Rowan", "아스펜|Aspen", "그웬|Gwen", "기네비어|Guinevere", "모건|Morgan", "마틸다|Matilda", "아그네스|Agnes", "베아트릭스|Beatrix", "거트루드|Gertrude", "헤드윅|Hedwig", "안드로메다|Andromeda", "아르테미시아|Artemisia", "제노비아|Zenobia", "부디카|Boudicca", "히폴리타|Hippolyta", "펜테실레이아|Penthesilea", "아탈란타|Atalanta", "스카아하|Scathach", "이졸데|Isolde", "발렌시아|Valencia", "빅토리아|Victoria", "알렉시아|Alexia", "안드레아|Andrea", "에리카|Erica", "프레데리카|Frederica", "레오나|Leona", "마르티나|Martina", "니콜|Nicole", "필리파|Philippa", "스테파니|Stephanie", "테오도라|Theodora", "빌마|Wilma", "브리토마트|Britomart", "안티오페|Antiope", "멜라니페|Melanippe", "오트레라|Otrera", "탈레스트리스|Thalestris", "미리나|Myrina", "리시페|Lysippe", "히폴리테|Hippolyte", "람페토|Lampeto", "마르페시아|Marpesia", "오리티아|Orithyia", "시노페|Sinope", "테르모도사|Thermodosa", "발라스카|Valasca", "블렌다|Blenda", "라게르타|Lagertha", "헤르보르|Hervor", "브륀힐드|Brynhildr", "시그드리파|Sigrdrifa", "스바바|Svava", "올룬|Olrun", "알비트|Alvitr", "흘라드군|Hladgunnr", "헤르야|Herja", "미스트|Mist", "스쿨드|Skuld", "랑그리드|Randgrid", "곤둘|Gondul", "게일뢰굴|Geirskogul", "스크뢰굴|Skogul"],
            s: ["아이언|Iron", "스틸|Steel", "쉴드|Shield", "소드|Sword", "블레이드|Blade", "스피어|Spear", "랜스|Lance", "액스|Axe", "해머|Hammer", "메이스|Mace", "보우|Bow", "애로우|Arrow", "대거|Dagger", "나이프|Knife", "가드|Guard", "센티넬|Sentinel", "워든|Warden", "키퍼|Keeper", "프로텍터|Protector", "디펜더|Defender", "챔피언|Champion", "워리어|Warrior", "파이터|Fighter", "솔저|Soldier", "나이트|Knight", "팔라딘|Paladin", "크루세이더|Crusader", "템플러|Templar", "레인저|Ranger", "스카우트|Scout", "스트롱|Strong", "볼드|Bold", "브레이브|Brave", "킨|Keen", "스위프트|Swift", "샤프|Sharp", "하드|Hard", "터프|Tough", "러프|Rough", "와일드|Wild", "힐트|Hilt", "폼멜|Pommel", "에지|Edge", "포인트|Point", "헬름|Helm", "건틀릿|Gauntlet", "그리브|Greave", "메일|Mail", "플레이트|Plate", "스트라이크|Strike", "배틀|Battle", "워|War", "파이트|Fight", "듀얼|Duel", "컴뱃|Combat", "빅토리|Victory", "글로리|Glory", "아너|Honor", "발러|Valor", "커리지|Courage", "스트롱홀드|Stronghold", "뱅가드|Vanguard", "불워크|Bulwark", "램파트|Rampart", "바스티온|Bastion", "시타델|Citadel", "포트리스|Fortress", "킵|Keep", "타워|Tower", "월|Wall", "게이트|Gate", "브릿지|Bridge", "모트|Moat", "드로우브릿지|Drawbridge", "포트컬리스|Portcullis", "애로우헤드|Arrowhead", "스피어포인트|Spearpoint", "블레이드에지|Bladeedge", "소드힐트|Swordhilt", "실드배쉬|Shieldbash", "아머|Armor", "퀴라스|Cuirass", "바이저|Visor", "맨틀|Mantle", "케이프|Cape", "클록|Cloak", "배너|Banner", "플래그|Flag", "스탠다드|Standard", "펜던트|Pennant"]
        },
        wizard: {
            m: ["멀린|Merlin", "알버스|Albus", "매그너스|Magnus", "코르넬리우스|Cornelius", "발타자르|Balthazar", "카스퍼|Casper", "멜키오르|Melchior", "아르키메데스|Archimedes", "피타고라스|Pythagoras", "유클리드|Euclid", "플라톤|Plato", "아리스토텔레스|Aristotle", "소크라테스|Socrates", "헤르메스|Hermes", "오딘|Odin", "로키|Loki", "토르|Thor", "제우스|Zeus", "포세이돈|Poseidon", "하데스|Hades", "아폴로|Apollo", "디오니소스|Dionysus", "아레스|Ares", "헤파이스토스|Hephaestus", "크로노스|Chronos", "우라노스|Uranus", "가이아|Gaia", "타이탄|Titan", "기간테스|Gigantes", "사이클롭스|Cyclops", "프로스페로|Prospero", "파우스트|Faust", "솔로몬|Solomon", "사이먼|Simon", "메이거스|Magus", "세이지|Sage", "시어|Seer", "오라클|Oracle", "프로핏|Prophet", "디바이너|Diviner", "아이올로스|Aeolus", "보레아스|Boreas", "노투스|Notus", "제피로스|Zephyrus", "히페리온|Hyperion", "이아페투스|Iapetus", "코이오스|Coeus", "크리우스|Crius", "오케아노스|Oceanus", "테티스|Tethys", "네레우스|Nereus", "프로테우스|Proteus", "트리톤|Triton", "아틀라스|Atlas", "프로메테우스|Prometheus", "에피메테우스|Epimetheus", "헬리오스|Helios", "셀레네|Selene", "에오스|Eos", "아스트라이오스|Astraeus", "조시모스|Zosimos", "자비르|Jabir", "파라켈수스|Paracelsus", "아그리파|Agrippa", "존디|Dee", "켈리|Kelly", "플라멜|Flamel", "로젠크로이츠|Rosencreutz", "아브라카다브라|Abra", "호커스|Hocus", "포커스|Pocus", "알케미스트|Alchemist", "네크로맨서|Necromancer", "서머너|Summoner", "컨저러|Conjurer", "인챈터|Enchanter", "일루셔니스트|Illusionist", "트랜스뮤터|Transmuter", "앱저러|Abjurer", "인보커|Invoker", "이보커|Evoker", "탈레스|Thales", "아낙시만드로스|Anaximander", "아낙시메네스|Anaximenes", "헤라클레이토스|Heraclitus", "파르메니데스|Parmenides", "엠페도클레스|Empedocles", "아낙사고라스|Anaxagoras", "데모크리토스|Democritus", "에피쿠로스|Epicurus"],
            f: ["모르가나|Morgana", "키르케|Circe", "메데이아|Medea", "헤카테|Hecate", "시빌|Sybil", "카산드라|Cassandra", "피티아|Pythia", "다프네|Daphne", "에코|Echo", "나르키소스|Narcissus", "프리야|Freyja", "이둔|Idun", "스카디|Skadi", "헬|Hel", "시프|Sif", "프리그|Frigg", "난나|Nanna", "에이르|Eir", "게피온|Gefion", "풀라|Fulla", "사가|Saga", "시긴|Sigyn", "노른|Norn", "발키리|Valkyrie", "엘프|Elf", "페어리|Fairy", "픽시|Pixie", "님프|Nymph", "드라이어드|Dryad", "세이렌|Siren", "메두사|Medusa", "스텐노|Stheno", "에우리알레|Euryale", "고르곤|Gorgon", "하피|Harpy", "스핑크스|Sphinx", "키메라|Chimera", "히드라|Hydra", "라미아|Lamia", "에키드나|Echidna", "플로라|Flora", "파우나|Fauna", "헤스티아|Hestia", "데메테르|Demeter", "페르세포네|Persephone", "레아|Rhea", "테미스|Themis", "므네모시네|Mnemosyne", "포이베|Phoebe", "테이아|Theia", "칼리오페|Calliope", "클리오|Clio", "에라토|Erato", "에우테르페|Euterpe", "멜포메네|Melpomene", "폴리힘니아|Polyhymnia", "테르프시코레|Terpsichore", "탈리아|Thalia", "우라니아|Urania", "네메시스|Nemesis", "시빌라|Sibylla", "볼바|Volva", "세이즈|Seidr", "파시파에|Pasiphae", "아리아드네|Ariadne", "파이드라|Phaedra", "프로크리스|Prokris", "필로멜라|Philomela", "프로크네|Procne", "알키오네|Alcyone", "케이릭스|Ceyx", "이오|Io", "세멜레|Semele", "다나에|Danae", "레다|Leda", "알크메네|Alcmene", "이오카스테|Jocasta", "안드로마케|Andromache", "헤쿠바|Hecuba", "폴릭세나|Polyxena", "크레우사|Creusa", "이피게네이아|Iphigeneia", "엘렉트라|Electra", "클리타임네스트라|Clytemnestra", "아트로포스|Atropos", "라케시스|Lachesis", "클로토|Clotho", "티시포네|Tisiphone", "메가라|Megaera", "알렉토|Alecto"],
            s: ["스타|Star", "문|Moon", "선|Sun", "스카이|Sky", "클라우드|Cloud", "레인|Rain", "스노우|Snow", "윈드|Wind", "스톰|Storm", "썬더|Thunder", "라이트닝|Lightning", "파이어|Fire", "워터|Water", "아이스|Ice", "어스|Earth", "네이처|Nature", "라이프|Life", "데스|Death", "스피릿|Spirit", "소울|Soul", "마인드|Mind", "타임|Time", "스페이스|Space", "보이드|Void", "카오스|Chaos", "오더|Order", "로직|Logic", "매직|Magic", "미스틱|Mystic", "아케인|Arcane", "코멧|Comet", "아스테로이드|Asteroid", "메테오|Meteor", "갤럭시|Galaxy", "네뷸라|Nebula", "코스모스|Cosmos", "유니버스|Universe", "월드|World", "플래닛|Planet", "플레인|Plane", "디멘션|Dimension", "렐름|Realm", "존|Zone", "에어리어|Area", "리전|Region", "스펠|Spell", "참|Charm", "헥스|Hex", "커스|Curse", "워드|Ward", "룬|Rune", "시길|Sigil", "글리프|Glyph", "마크|Mark", "사인|Sign", "오라|Aura", "마나|Mana", "에테르|Ether", "에센스|Essence", "엘리먼트|Element", "스타라이트|Starlight", "문라이트|Moonlight", "선라이트|Sunlight", "스타더스트|Stardust", "문더스트|Moondust", "선더스트|Sundust", "스타파이어|Starfire", "문파이어|Moonfire", "선파이어|Sunfire", "스타샤인|Starshine", "문빔|Moonbeam", "선빔|Sunbeam", "스타폴|Starfall", "문라이즈|Moonrise", "선라이즈|Sunrise", "스타워치|Starwatch", "문워치|Moonwatch", "선워치|Sunwatch", "트와일라잇|Twilight", "더스크|Dusk", "던|Dawn", "미드나잇|Midnight", "눈|Noon", "이클립스|Eclipse", "솔스티스|Solstice", "이쿼녹스|Equinox", "호라이즌|Horizon", "제니스|Zenith", "나디르|Nadir", "오로라|Aurora"]
        },
        commoner: {
            m: ["존|John", "제임스|James", "톰|Tom", "잭|Jack", "빌|Bill", "밥|Bob", "샘|Sam", "댄|Dan", "폴|Paul", "마크|Mark", "루크|Luke", "매튜|Matthew", "피터|Peter", "앤드류|Andrew", "필립|Philip", "토마스|Thomas", "조셉|Joseph", "찰스|Charles", "데이비드|David", "리차드|Richard", "로버트|Robert", "윌리엄|William", "조지|George", "에드워드|Edward", "헨리|Henry", "프랭크|Frank", "해리|Harry", "스티브|Steve", "아담|Adam", "벤|Ben", "제이콥|Jacob", "마이클|Michael", "조슈아|Joshua", "다니엘|Daniel", "크리스토퍼|Christopher", "안소니|Anthony", "도널드|Donald", "케네스|Kenneth", "스티븐|Steven", "브라이언|Brian", "로날드|Ronald", "케빈|Kevin", "제이슨|Jason", "제프리|Jeffrey", "라이언|Ryan", "게리|Gary", "니콜라스|Nicholas", "에릭|Eric", "조나단|Jonathan", "저스틴|Justin", "스콧|Scott", "브랜든|Brandon", "벤자민|Benjamin", "사무엘|Samuel", "그레고리|Gregory", "알렉산더|Alexander", "패트릭|Patrick", "레이몬드|Raymond", "데니스|Dennis", "제리|Jerry", "랄프|Ralph", "로저|Roger", "로이|Roy", "러셀|Russell", "세스|Seth", "쉐인|Shane", "숀|Shawn", "사이먼|Simon", "스펜서|Spencer", "스탠리|Stanley", "스튜어트|Stuart", "테드|Ted", "테리|Terry", "팀|Tim", "티모시|Timothy", "토비|Toby", "토드|Todd", "토니|Tony", "빈센트|Vincent", "웨인|Wayne", "더글라스|Douglas", "유진|Eugene", "로렌스|Lawrence", "가브리엘|Gabriel", "오스틴|Austin", "칼|Carl", "크리스|Chris", "카메론|Cameron", "코너|Connor", "케일럽|Caleb"],
            f: ["메리|Mary", "안나|Anna", "엠마|Emma", "사라|Sarah", "엘리스|Alice", "루시|Lucy", "그레이스|Grace", "로즈|Rose", "릴리|Lily", "제인|Jane", "케이트|Kate", "줄리|Julie", "에이미|Amy", "리사|Lisa", "베티|Betty", "헬렌|Helen", "도로시|Dorothy", "마가렛|Margaret", "루스|Ruth", "클라라|Clara", "에밀리|Emily", "소피|Sophie", "미아|Mia", "클로이|Chloe", "아리아|Aria", "조이|Zoe", "노라|Nora", "아이비|Ivy", "루나|Luna", "벨라|Bella", "패트리샤|Patricia", "제니퍼|Jennifer", "린다|Linda", "엘리자베스|Elizabeth", "바바라|Barbara", "수잔|Susan", "제시카|Jessica", "카렌|Karen", "낸시|Nancy", "산드라|Sandra", "애슐리|Ashley", "킴벌리|Kimberly", "도나|Donna", "미셸|Michelle", "캐롤|Carol", "아만다|Amanda", "멜리사|Melissa", "데보라|Deborah", "스테파니|Stephanie", "레베카|Rebecca", "로라|Laura", "샤론|Sharon", "신시아|Cynthia", "캐슬린|Kathleen", "셜리|Shirley", "에이미|Amy", "안젤라|Angela", "브렌다|Brenda", "파멜라|Pamela", "니콜|Nicole", "샐리|Sally", "사만다|Samantha", "사샤|Sasha", "스칼렛|Scarlett", "셀레나|Selena", "세레나|Serena", "섀넌|Shannon", "쉴라|Sheila", "쉐리|Sherry", "실비아|Silvia", "시몬|Simone", "소니아|Sonia", "스테이시|Stacy", "스텔라|Stella", "수|Sue", "수잔|Suzanne", "티나|Tina", "트레이시|Tracy", "바네사|Vanessa", "웬디|Wendy", "이본|Yvonne", "오드리|Audrey", "비벌리|Beverly", "다이앤|Diane", "에블린|Evelyn", "글로리아|Gloria", "헤이즐|Hazel", "주디|Judy", "루이스|Lois", "마사|Martha"],
            s: ["스미스|Smith", "밀러|Miller", "베이커|Baker", "쿡|Cook", "피셔|Fisher", "헌터|Hunter", "카펜터|Carpenter", "테일러|Taylor", "위버|Weaver", "터너|Turner", "쿠퍼|Cooper", "메이슨|Mason", "포터|Potter", "바버|Barber", "가드너|Gardner", "파머|Farmer", "셰퍼드|Shepherd", "카터|Carter", "라이트|Wright", "워커|Walker", "홀|Hall", "힐|Hill", "우드|Wood", "그린|Green", "브라운|Brown", "화이트|White", "블랙|Black", "롱|Long", "쇼트|Short", "영|Young", "플레처|Fletcher", "소이어|Sawyer", "태너|Tanner", "브루어|Brewer", "슬레이터|Slater", "대처|Thatcher", "챈들러|Chandler", "콜리어|Collier", "웹스터|Webster", "스쿠너|Schooner", "웨이너|Wainer", "파커|Parker", "브룩|Brook", "리버|River", "레이크|Lake", "폰드|Pond", "풀|Pool", "웰|Well", "스프링|Spring", "스트림|Stream", "포레스트|Forest", "그로브|Grove", "오차드|Orchard", "가든|Garden", "파크|Park", "메도우|Meadow", "필드|Field", "무어|Moor", "히스|Heath", "마쉬|Marsh", "플라우맨|Ploughman", "허즈맨|Herdsman", "파울러|Fowler", "포레스터|Forester", "조이너|Joiner", "휠라이트|Wheelwright", "웨인라이트|Wainwright", "카트라이트|Cartwright", "머서|Mercer", "드레이퍼|Draper", "스킨너|Skinner", "새들러|Saddler", "슈메이커|Shoemaker", "코블러|Cobbler", "아이언|Iron", "스톤|Stone", "브릭|Brick", "애쉬|Ash", "버치|Birch", "오크|Oak", "엘름|Elm", "파인|Pine", "메이플|Maple", "시더|Cedar", "쏜|Thorn", "베리|Berry", "부시|Bush", "헤지|Hedge", "반스|Barnes", "브릿지스|Bridges"]
        },
        servant: {
            m: ["핍|Pip", "돕|Dob", "키퍼|Kiper", "니모|Nimo", "토비|Toby", "로빈|Robin", "퍽|Puck", "바니|Barney", "테디|Teddy", "빌리|Billy", "지미|Jimmy", "티미|Timmy", "토미|Tommy", "바비|Bobby", "베니|Benny", "리키|Ricky", "미키|Micky", "니키|Nicky", "비키|Vicky", "코코|Coco", "모모|Momo", "토토|Toto", "루루|Lulu", "페페|Pepe", "포포|Popo", "칩|Chip", "스킵|Skip", "플립|Flip", "트립|Trip", "닙|Nip", "십|Sip", "딥|Dip", "립|Lip", "힙|Hip", "팁|Tip", "빈|Bean", "넛|Nut", "시드|Seed", "콘|Corn", "라이스|Rice", "오트|Oat", "위트|Wheat", "라이|Rye", "발리|Barley", "몰트|Malt", "쿠키|Cookie", "크래커|Cracker", "머핀|Muffin", "도넛|Donut", "베이글|Bagel", "번|Bun", "롤|Roll", "타트|Tart", "파이|Pie", "케이크|Cake", "빕|Bip", "밥|Bop", "빔|Bim", "밤|Bam", "봄|Bom", "법|Bub", "빕|Bib", "밥|Bab", "뱁|Beb", "펍|Pup", "팝|Pop", "펩|Pep", "팹|Pap", "덤|Dum", "디|Dee", "두|Doo", "다|Dah", "야|Yah", "요|Yo", "유|Yu", "와|Wa", "워|Wo", "위|We", "지|Zi", "주|Zu", "제|Ze", "자|Za", "기|Gi", "구|Gu", "개|Ga"],
            f: ["미미|Mimi", "나나|Nana", "리리|Lili", "슈슈|Shushu", "치치|Chichi", "코코|Coco", "비비|Bibi", "라라|Lala", "디디|Didi", "키키|Kiki", "티티|Titi", "지지|Gigi", "피피|Pipi", "메메|Meme", "네네|Nene", "로로|Roro", "소소|Soso", "요요|Yoyo", "주주|Juju", "차차|Chacha", "카카|Kaka", "타타|Tata", "파파|Papa", "하하|Haha", "호호|Hoho", "피피|Fifi", "시시|Sisi", "비비|Vivi", "리리|Riri", "지지|Zizi", "베베|Bebe", "세세|Cece", "데데|Dede", "키키|Kiki", "미미|Mimi", "로즈|Rose", "릴리|Lily", "데이지|Daisy", "튤립|Tulip", "팬지|Pansy", "피오니|Peony", "오키드|Orchid", "로터스|Lotus", "재스민|Jasmine", "아이리스|Iris", "바이올렛|Violet", "포피|Poppy", "메리골드|Marigold", "홀리|Holly", "아이비|Ivy", "펀|Fern", "모스|Moss", "클로버|Clover", "민트|Mint", "바질|Basil", "파파|Fafa", "푸푸|Fufu", "페페|Fefe", "사사|Sasa", "수수|Susu", "세세|Sese", "바바|Vava", "부부|Vuvu", "베베|Veve", "자자|Zaza", "주주|Zuzu", "제제|Zeze", "나나|Nona", "니나|Nina", "누누|Nunu", "네네|Nene", "마마|Mama", "무무|Mumu", "메메|Meme", "라라|Lara", "루루|Lulu", "레레|Lele", "카카|Kaka", "쿠쿠|Kuku", "케케|Keke", "타타|Tata", "투투|Tutu", "테테|Tete", "와와|Wawa", "우우|Wuwu"],
            s: ["(성 없음)|", "(성 없음)|", "(성 없음)|", "(성 없음)|", "(성 없음)|", "풋|Foot", "핸드|Hand", "아이|Eye", "이어|Ear", "노즈|Nose", "마우스|Mouth", "헤드|Head", "암|Arm", "레그|Leg", "핑거|Finger", "토|Toe", "바디|Body", "백|Back", "벨리|Belly", "헤어|Hair", "스킨|Skin", "본|Bone", "블러드|Blood", "하트|Heart", "마인드|Mind", "페블|Pebble", "스톤|Stone", "락|Rock", "샌드|Sand", "더스트|Dust", "더트|Dirt", "머드|Mud", "클레이|Clay", "실트|Silt", "로암|Loam", "그래블|Gravel", "볼더|Boulder", "브릭|Brick", "타일|Tile", "슬레이트|Slate", "우드|Wood", "로그|Log", "스틱|Stick", "브랜치|Branch", "트위그|Twig", "리프|Leaf", "루트|Root", "바크|Bark", "스템|Stem", "쏜|Thorn", "씨드|Seed", "넛|Nut", "쉘|Shell", "허스크|Husk", "필|Peel", "크럼|Crumb", "스펙|Speck", "닷|Dot", "모트|Mote", "플렉|Fleck", "비트|Bit", "스크랩|Scrap", "샤드|Shard", "칩|Chip", "프래그먼트|Fragment", "피스|Piece", "파트|Part", "포션|Portion", "섹션|Section", "슬라이스|Slice", "청크|Chunk", "럼프|Lump", "클럼프|Clump", "와드|Wad", "헝크|Hunk", "드롭|Drop", "비드|Bead", "블롭|Blob", "글롭|Glob", "대쉬|Dash", "핀치|Pinch", "스미전|Smidgen", "트레이스|Trace", "힌트|Hint", "위스퍼|Whisper"]
        }
    },
    wuxia: {
        noble: {
            m: ["청명", "백운", "무진", "자운", "태을", "천우", "명운", "진천", "호연", "상현", "운룡", "현진", "도현", "문기", "학규", "소유", "건영", "시운", "규화", "단우", "청운", "유성", "비천", "무경", "현도", "자하", "일청", "소백", "운엽", "천기", "형운", "지학", "현무", "청허", "무영", "진우", "경수", "태산", "운중", "호영", "천광", "낙운", "시현", "규연", "백천", "송운", "학진", "유도", "현성", "진혁", "운현", "상원", "수현", "경운", "도원", "무극", "청람", "화운", "진명", "천위"],
            f: ["소연", "화린", "청아", "유란", "백설", "자령", "명주", "설화", "예린", "유화", "빙예", "소향", "채령", "은설", "수련", "홍련", "단영", "미령", "소월", "자하", "연희", "서연", "비란", "아영", "청조", "유리", "가을", "설지", "화영", "난향", "옥련", "수아", "지선", "혜진", "나영", "우희", "소선", "비연", "현주", "월희", "금선", "채운", "소유", "명하", "진주", "설희", "운령", "청유", "하늘", "은하"],
            s: ["남궁", "제갈", "모용", "황보", "사마", "독고", "선우", "상관", "구양", "야율", "공손", "서문", "동방", "헌원", "하후", "우문", "백리", "북궁", "자말", "단목", "진", "백", "이", "왕", "유", "장", "운", "풍", "뇌", "임", "한", "조", "송", "정", "양", "하", "오", "서", "윤", "강", "고", "원", "곽", "주", "채"]
        },
        villain: {
            m: ["혈비", "천악", "무결", "광현", "패천", "마령", "독심", "살혼", "광마", "염라", "흑주", "사신", "파천", "멸혼", "귀영", "악살", "혈풍", "마진", "독수", "잔월", "패왕", "천살", "극도", "흑룡", "사혈", "무명", "귀면", "뇌옥", "광도", "음마", "혈랑", "적운", "혼세", "단죄", "야차", "수라", "참격", "멸천", "흉수", "사패", "독룡", "무혈", "살겁", "천마", "지옥", "폭염", "괴수", "참혈", "환마", "혈광"],
            f: ["홍련", "요화", "흑조", "매구", "독희", "사녀", "혈매", "음희", "마설", "자요", "비월", "천요", "염희", "적련", "귀비", "독란", "야희", "유명", "살희", "흑접", "혈희", "몽마", "환희", "절영", "마예", "소살", "음령", "적화", "요란", "무염", "비사", "혈주", "독연", "암향", "사령", "흑련", "괴희", "참아", "멸화", "주란"],
            s: ["마", "독고", "음", "사", "천", "혈", "장", "흑", "배", "염", "귀", "야", "폭", "살", "뇌", "묵", "견", "나", "방", "위", "당", "팽", "설", "금", "전", "반", "시", "감", "동", "악", "형", "몽", "좌", "우", "표", "양", "명"]
        },
        warrior: {
            m: ["비룡", "일도", "무진", "광현", "철심", "단우", "검진", "소룡", "태산", "무비", "검한", "도전", "광도", "철산", "풍진", "한수", "고검", "낭천", "벽산", "취선", "단운", "검마", "패도", "무상", "유협", "진검", "천호", "질풍", "번개", "무식", "철우", "강철", "호걸", "용비", "백호", "청룡", "비검", "단월", "무신", "고영", "한비", "천랑", "월풍", "적호", "뇌전", "쾌검", "환검", "무정", "잠룡", "풍운"],
            f: ["검희", "무영", "비연", "채령", "월영", "소월", "은설", "미령", "단영", "소향", "명월", "청설", "한월", "유성", "비령", "검향", "무란", "설검", "청향", "은비", "비화", "월하", "단심", "연무", "호연", "진아", "설란", "청빙", "여협", "비단", "운검", "향무", "소협", "자영", "혜검", "무소", "월아", "청련", "비취", "단향"],
            s: ["곽", "하", "한", "임", "차", "고", "석", "주", "양", "표", "설", "홍", "배", "전", "노", "문", "방", "성", "오", "육", "지", "허", "현", "추", "단", "묵", "공", "감", "탁", "위", "모", "편", "국", "어", "용", "남", "비", "도"]
        }
    },
    korean: {
        modern: {
            m: ["민준", "서준", "도윤", "예준", "시우", "하준", "지호", "주원", "지후", "준우", "준서", "도현", "건우", "현우", "우진", "지훈", "선우", "유준", "서진", "연우", "은우", "민재", "현준", "시윤", "정우", "이준", "승우", "윤우", "지환", "지우", "승현", "유찬", "준혁", "수호", "승민", "시후", "진우", "민성", "준영", "수현", "지원", "이안", "재윤", "시현", "태윤", "한결", "지안", "동현", "윤호", "시원", "은찬", "시온", "민우", "재원", "민규", "지한", "서우", "은호", "재민", "민찬", "우주", "우빈", "하율", "준호", "지율", "성민", "승준", "하진", "성현", "재현", "현서", "민호", "태민", "예성", "지성", "지민", "윤재", "태현", "민혁", "하람", "도훈", "이든", "지오", "강민", "지완", "태준", "준성", "하랑", "승원", "도영", "현수", "정현", "승호", "도율", "시율", "성빈", "우현", "시훈", "민서", "서율", "건희", "시완", "주환", "라온", "원준", "민수", "정훈", "태오", "현민", "승윤", "동하", "민기", "재하", "주영", "도경", "서후", "단우", "경민", "민건", "현성", "시환", "시안", "도원", "정후", "가온", "온유", "승빈", "정원", "호준", "태훈", "재준", "재훈", "태영", "세현", "동건", "연준", "태경", "도준", "유건", "범준", "하온", "찬영", "태율", "현진", "재영", "영준", "성윤", "하윤", "현승", "주혁", "상현", "찬우", "지혁", "세준", "승훈", "하늘", "승재", "동윤", "우성", "건호", "태호", "찬희", "윤찬", "윤후", "성훈", "유안", "지운", "연호", "수민", "서호", "유현", "동욱", "승찬", "도겸", "태우", "규빈", "현호", "주한", "서원", "재우", "현빈", "재희", "수혁", "주완", "유진", "효준", "우찬", "시헌", "주현", "준석", "은율", "재혁", "동우", "선호", "형준", "이한", "성우", "상윤", "도진", "우영"],
            f: ["서연", "민서", "지우", "서윤", "하은", "지안", "수아", "하린", "유나", "서아", "채원", "지유", "다인", "예은", "수빈", "시아", "소율", "아린", "다은", "나은", "유진", "지원", "예린", "지은", "수진", "은지", "민지", "윤아", "채은", "가은", "서현", "예진", "서영", "지민", "예원", "윤서", "소윤", "지현", "하윤", "은우", "현지", "채우", "예지", "시은", "민주", "다연", "연우", "수민", "채아", "다온", "지아", "시현", "주하", "승연", "서진", "서은", "나윤", "채연", "예나", "민채", "다현", "가윤", "하율", "정원", "태희", "도연", "시연", "서율", "은서", "예빈", "지윤", "나연", "예림", "연서", "하영", "수현", "규리", "아인", "은채", "주아", "소은", "서우", "유주", "윤지", "다솜", "소민", "지온", "사랑", "예서", "채원", "유빈", "가온", "지안", "설아", "수아", "이서", "이수", "이안", "이빈", "이현", "나은", "하온", "하진", "주은", "채민", "채빈", "채이", "채윤", "채율", "채은", "태리", "태린", "태연", "태은", "태이", "태인", "태희", "하늘", "하나", "하루", "하리", "하민", "하서", "하솔", "하연", "하영", "하온", "하윤", "하은", "하진", "한나", "한별", "한비", "한솔", "한이", "해나", "해린", "해수", "해온", "해윤", "해인", "현서", "현수", "현아", "현영", "현유", "현주", "현지", "혜나", "혜린", "혜민", "혜빈", "혜서", "혜수", "혜연", "혜영", "혜원", "혜윤", "혜인", "혜주"],
            s: ["김", "이", "박", "정", "최", "조", "강", "윤", "장", "임", "신", "유", "한", "오", "서", "전", "권", "황", "안", "송", "홍", "양", "고", "문", "손", "배", "백", "허", "노", "남", "심", "하", "주", "구", "곽", "성", "차", "우", "진", "민", "류", "나", "지", "엄", "변", "채", "원", "방", "천", "공", "현", "함", "여", "염", "석", "추", "도", "소", "설", "선", "마", "길", "연", "위", "표", "명", "기", "반", "라", "왕", "금", "옥", "육", "인", "맹", "제", "모", "탁", "국", "어", "경", "은", "편", "용", "예", "봉", "사", "부", "가", "복", "태", "목", "형", "피", "두", "감", "호", "제갈", "남궁", "독고", "선우", "황보"]
        },
        classic: {
            m: ["영수", "영호", "영식", "영철", "정수", "정호", "정식", "정훈", "성수", "성호", "성훈", "성진", "철수", "철호", "철민", "민수", "민호", "민철", "만수", "동수", "동현", "동훈", "진수", "진호", "준호", "준수", "광수", "광호", "상훈", "상우", "상철", "병철", "병수", "재호", "재석", "경수", "종수", "종호", "종훈", "명수", "명호", "현수", "현우", "현철", "기수", "기철", "석수", "석호"],
            f: ["영희", "영숙", "영자", "영순", "정숙", "정희", "정순", "정자", "순자", "순희", "순정", "미숙", "미경", "미영", "미자", "미희", "경숙", "경희", "경자", "경순", "혜자", "혜숙", "혜경", "혜영", "혜정", "희자", "희숙", "희경", "희정", "숙자", "숙희", "명자", "명숙", "명희", "현숙", "현정", "현주", "현희", "은주", "은영", "은숙", "은경", "은희", "지영", "지숙", "지현", "지혜", "수진"],
            s: ["김", "이", "박", "최", "정", "강", "조", "윤", "장", "임", "한", "오", "서", "전", "권", "황", "안", "송", "홍", "양", "고", "문", "손", "배", "백", "허", "유", "남", "심", "노"]
        }
    }
};
window.NAME_ROLES = {
    fantasy: [
        { id: 'royalty', text: '👑 왕족 / 고위 귀족' },
        { id: 'knight', text: '⚔️ 기사 / 전사' },
        { id: 'wizard', text: '✨ 마법사 / 현자' },
        { id: 'commoner', text: '🔨 평민 / 상인' },
        { id: 'servant', text: '🧹 하인 / 크리처' }
    ],
    wuxia: [
        { id: 'noble', text: '🏯 명문 세가 / 정파' },
        { id: 'villain', text: '😈 사파 / 마교' },
        { id: 'warrior', text: '🗡️ 낭인 / 협객' }
    ],
    korean: [
        { id: 'modern', text: '📱 현대적 / 트렌디' },
        { id: 'classic', text: '📺 전통적 / 중후함' }
    ]
};